# Generated by Django 5.1.2 on 2024-10-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('is_admin', models.BooleanField(default=True)),
                ('password', models.CharField()),
            ],
        ),
    ]
